export const sources = [
  {
    id: 'us-counties',
    config: {
      type: 'vector',
      url: 'mapbox://ruokvl.0761cl0n',
      promoteId: 'FEATURE_ID',
    },
  },
  {
    id: 'us-county-centroids',
    config: {
      type: 'geojson',
      data: '/api/us-county-centroids',
    },
  },
];
export const layers = [
  {
    id: 'us-county-total-deaths',
    type: 'fill',
    source: 'us-counties',
    'source-layer': 'us-counties-500k-a4l482',
    paint: {
      'fill-color': '#f00',
      'fill-opacity': [
        'interpolate',
        ['linear'],
        ['feature-state', 'deaths'],
        0,
        0,
        1,
        0.1,
        10,
        0.2,
        100,
        0.4,
        1000,
        0.7,
        2000,
        0.8,
        10000000,
        0.8,
      ],
    },
  },
  {
    id: 'us-county-total-cases',
    type: 'fill',
    source: 'us-counties',
    'source-layer': 'us-counties-500k-a4l482',
    paint: {
      'fill-color': '#00f',
      'fill-opacity': [
        'interpolate',
        ['linear'],
        ['feature-state', 'cases'],
        0,
        0,
        10,
        0.1,
        100,
        0.2,
        10000,
        0.4,
        100000,
        0.7,
        200000,
        0.8,
        10000000,
        0.8,
      ],
    },
  },
  {
    id: 'us-counties-base',
    legendHide: true,
    type: 'fill',
    source: 'us-counties',
    'source-layer': 'us-counties-500k-a4l482',
    paint: {
      'fill-outline-color': '#0f0',
      'fill-color': 'rgba(0, 255, 0, 1)',
      'fill-opacity': ['to-number', ['feature-state', 'active']],
    },
  },
  {
    id: 'us-first-case',
    legendHide: false,
    type: 'symbol',
    source: 'us-county-centroids',
    layout: {
      'icon-image': 'corona-green',
      'icon-size': 0.3,
      'icon-ignore-placement': true,
    },
    paint: {
      'icon-opacity': ['to-number', ['feature-state', 'firstCase']],
      'icon-color': 'red',
    },
  },
  {
    id: 'us-county-names',
    legendHide: true,
    type: 'symbol',
    source: 'us-county-centroids',
    minzoom: 7,
    layout: { 'text-field': ['get', 'NAME'], 'text-ignore-placement': true },
    paint: {
      'text-halo-color': '#fff',
      'text-halo-width': 1,
    },
  },
];
