
name: covidmap

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'chore/**'
      - 'bugfix/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn

    - name: lint
      run: yarn lint

    - name: test
      run: yarn test
